version: '3.7'
services:
  redis:
    image: redis:alpine
    #command: redis-server redis.conf
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"
  db:
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    env_file:
      - ./.env
    command: sh -c "python -m src.bot"

    restart: always
    depends_on:
      - db
      - redis

volumes:
  pgdata:
