version: '3.7'
services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    image: postgres:14-alpine
    restart: on-failure
    volumes:
      - pgdata:/home/ubuntu/postgres/data


volumes:
  pgdata: